using CriScope.App;
using CriScope.Core;

int checks = 0;
void Check(bool value, string message) { if (!value) throw new Exception(message); checks++; }
WireEvent E(string kind, string entity, string id, double time, string parent = "", long seq = 0) => new() { kind=kind, entity=entity, objectId=id, time=time, parentId=parent, seq=seq, name="Cue" };
PlaybackGroup One(params WireEvent[] e) => PlaybackPresentation.Group(e, 20).Single();
var request = E("request", "cue", "p1", 1, "player1", 10);
var voice = E("play", "voice", "v1", 1.1, "p1", 11);
var stop = E("stop", "voice", "v1", 3.1, "p1", 14);
var release = E("log", "cue", "p1", 3.2, seq:15); release.lifecycle="released";
var active = One(request, voice);
Check(active.StatusLabel=="播放中" && active.ActiveVoiceCount==1, "零音量默认值仍是正常播放实例");
Check(active.RequestAt==1 && active.StartedAt==1.1 && active.DurationAt(2.1)==1, "请求与实际Voice开始分开");
Check(One(request).StatusLabel=="等待 Voice 分配" && One(request).StartedAt==null, "单独请求不伪造播放开始");
var done = One(request, voice, stop, release);
Check(done.StatusLabel=="已结束" && done.ActiveVoiceCount==0, "完整释放闭合播放状态");
Check(Math.Abs(done.DurationAt(20)!.Value-2)<0.000001 && done.EndedAt==3.1 && done.InstanceEndedAt==3.2, "末Voice释放与实例释放各有时间");
Check(Math.Abs(done.InstanceDurationAt(20)!.Value-2.2)<0.000001, "实例历时不冒充Voice历时");
Check(One(request,voice,stop).StatusLabel=="声部已结束 · 实例待结束", "声部结束不能伪造实例释放");
var gap=E("gap", "", "", 2, seq:13);
Check(One(request,voice,gap).StatusLabel.Contains("待确认") && One(request,voice,gap).DurationAt(20)==null, "真实缺口阻止无根据播放状态及历时");
Check(One(request,voice,stop,release,E("gap","","",4)).StatusLabel=="已结束", "结束后的缺口不污染历史实例");
Check(One(stop).UnknownStart && One(stop).StartedAt==null, "只见释放不猜开始");
var prior=E("play","voice","prior",1,"p1"); prior.detail="连接时已存在 Voice；起点未知";
Check(One(request,prior).UnknownStart && One(request,prior).StartedAt==null && One(request,prior).StatusLabel=="播放中", "热连接的活动Voice保留活动状态而起点未知");
var lateRequest=E("request","cue","p2",4,"player1");
Check(PlaybackPresentation.Group([request,voice,lateRequest],20).Length==2, "同名Cue不合并实例");
var limit=E("stop","cue","p1",1.05); limit.lifecycle="stopped";limit.endReason="playback-limit";limit.causeId="p2";
var limited=One(request,limit,release);
Check(limited.StatusLabel=="数量限制终止" && limited.CausePlaybackId=="p2", "数量限制及触发实例明确");
Check(limited.InstanceEndedAt==1.05 && limited.InstanceReleasedAt==3.2 && limited.DurationAt(20)==null, "限制发生与释放分开，无Voice不产生历时");
var legacy=E("log","cue","p1",3.2);legacy.detail="CRI 播放实例释放";
Check(One(request,voice,stop,legacy).StatusLabel=="已结束", "兼容旧录制的释放");
Check(One(request,voice,release).DurationAt(20)==null && One(request,voice,release).StatusLabel=="已结束", "实例结束但Voice结束缺失不伪造Voice历时");
var oldLimit=E("log","","1:playback:1:167",2);oldLimit.name="ExCue_StopByLimit";
oldLimit.raw="""{"function":"ExCue_StopByLimit","parameters":[{"name":"ExPlaybackId_unique64","value":167},{"name":"cause ExPlaybackId_unique64","value":168}]}""";
Check(One(oldLimit).CausePlaybackId=="1:playback:1:168" && One(oldLimit).StatusLabel=="数量限制终止", "旧原生限制日志保留关联前缀");
var a0=E("aisac","control","player1",0.5); a0.name="Volume";a0.value=0.2;
var a1=E("aisac","control","player1",2);a1.name="Volume";a1.value=0.4;
var a2=E("aisac","control","player1",4);a2.name="Volume";a2.value=0.8;
var wrong=E("aisac","control","player2",0.6);wrong.name="Volume";wrong.value=1;
var beat=E("beat","control","p1",2.5);
var wrongBeat=E("beat","control","p2",2.5);
var controls=PlaybackPresentation.ControlsFor(done,[a0,a1,a2,wrong,beat,wrongBeat],20);
Check(controls.BeforeStart.Single()==a0, "旧实例显示开始前设置，不倒填未来Source设置");
Check(controls.DuringPlayback.Length==2 && controls.DuringPlayback.Contains(a1) && controls.DuringPlayback.Contains(beat), "变化及节拍按Player/实例与生命周期关联");
Check(PlaybackPresentation.ControlsFor(done,[a0,E("gap","","",0.9)],20).BeforeStart.Length==0, "开始前缺口清除不可信设置快照");
var selector=E("selector","control","player1",0.3);selector.name="Foot";selector.detail="Stone";
var clear=E("selector","control","player1",0.4);clear.name="全部 Selector";clear.detail="清除全部选择";
var selected=PlaybackPresentation.ControlsFor(done,[selector,clear,a0],20).BeforeStart;
Check(!selected.Contains(selector) && selected.Contains(clear), "Selector清除不会残留旧标签");
var overlapping=E("play","voice","v2",2,"p1");var overlappingEnd=E("stop","voice","v2",4,"p1");
Check(One(request,voice,stop,overlapping,overlappingEnd).EndedAt==4, "多Voice以最后一个释放为末端");
var nativeRequest=E("request","cue","native",1,"player1");nativeRequest.session="native";nativeRequest.channel="native";
var nativeVoice=E("play","voice","nv",1.1,"native");nativeVoice.session="native";nativeVoice.channel="native";
var sdkGap=E("gap","","",2);sdkGap.session="sdk";sdkGap.channel="sdk";
Check(One(nativeRequest,nativeVoice,sdkGap).StatusLabel=="播放中", "SDK缺口不污染原生Voice状态");
var sdkEarlyGap=E("gap","","",0.9);sdkEarlyGap.session="sdk";sdkEarlyGap.channel="sdk";
Check(PlaybackPresentation.ControlsFor(One(nativeRequest,nativeVoice),[a0,sdkEarlyGap],20).BeforeStart.Contains(a0), "SDK缺口不清除原生Player历史设置");
Check(One(release).StatusLabel.Contains("记录不完整"), "只有Cue结束时不宣称从未分配Voice");
Console.WriteLine($"Playback presentation checks passed: {checks}");
